---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}

```

## Types of commuting transportation by age (header 2)

The relationship between the type of commuting transportation and the age of respondents

```{r}
library(tidyverse)
logged_data <- read_csv(paste0("https://docs.google.com/spreadsheets",
"/d/e/2PACX-1vSm22IrT9r0H6mTjF-PlbhIhQbCKsC6ruOW8G2s_7raorH2YrdRFRr0wy",
"l4YVUyNG67YROGVoDFOV01/pub?output=csv"))

latest_data <- rename(logged_data)

glimpse(latest_data)

a <- tibble(commuting = latest_data$`Do you use trasportation for commuting?`, age = latest_data$`What is your age?`)

b <- tibble(transporation_type = latest_data$`What is your type of trasportation for commuting`, 
age = latest_data$`What is your age?`)
glimpse(b)

#Calculating the total number of respondents
num_people <- length(latest_data$`What is your age?`)

#Calculating the total number of respondents, excluding no commuters


paste("The total number of respondents is", num_people, "people")

#Calculating the average age of respondents of my data
average_age <- (sum(latest_data$`What is your age?`) / num_people) %>% round

(latest_data$`What is your age?`) %>% mean()

#num_commuter <- latest_data$`What is your age?` %>% 
#  length(na.rm = TRUE)
#latest_data$binary_commute <- ifelse(
#  latest_data$`Do you use transportation for commuting?` == "Yes", 1,
#  ifelse(latest_data$`Do you use transportation for commuting?` == "No", 0, NA))


# Calculate the mean of the binary variable
num_commuter <- mean(latest_data$binary_commute, na.rm = TRUE)

paste("The average age of respondents is", average_age)

#Calculating the maximum and minimum age value 
min(latest_data$`what is your age?`)
max(latest_data$`what is your age?`)

#Creating a bar chart between the number of respondents and the commuting status

a %>%
  ggplot() +
  geom_bar(aes(x = commuting), fill = '#33ddff') +
  labs(title = "The number of commuters",
       subtitle = "demonstrating of commuting status",
       caption = "Source: Google form survery by Lucas Kang",
       x = "Commuting status",
       y = "The number of commuter")




a



```


```{r}
#Creating a bar chart between respondents' age and 
#the type of transportation for commuting

b %>%
  ggplot() +
  geom_bar(aes(x = age, fill = transporation_type)) +
  labs(title = "Transportaion type for commuting by age",
       subtitle = "Comparing transportaion type and age for commuters",
       caption = "Source: Google form survery by Lucas Kang",
       x = "Age (New Zealand Legal age)",
       y = "Type of transportation")

b
```
The total number of respondents is `r num_people` and the number of commuters is `num_commuter`. 
